#!/bin/bash
mysql --user=root --password= -e "UPDATE mysql.user SET Password = PASSWORD('cloudera') WHERE User = 'root'"
mysql --user=root --password= -e "DROP USER ''@'localhost'"
mysql --user=root --password= -e "DROP USER ''@'$(hostname)'"
mysql --user=root --password= -e "DROP DATABASE test"
mysql --user=root --password= -e "CREATE DATABASE scm DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci"
mysql --user=root --password= -e "GRANT ALL ON scm.* TO 'scm'@'%' IDENTIFIED BY 'cloudera'"
mysql --user=root --password= -e "CREATE DATABASE rman DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci"
mysql --user=root --password= -e "GRANT ALL ON rman.* TO 'rman'@'%' IDENTIFIED BY 'cloudera'"
mysql --user=root --password= -e "CREATE DATABASE hue DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci"
mysql --user=root --password= -e "GRANT ALL ON hue.* TO 'hue'@'%' IDENTIFIED BY 'cloudera'"
mysql --user=root --password= -e "CREATE DATABASE metastore DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci"
mysql --user=root --password= -e "GRANT ALL ON metastore.* TO 'hive'@'%' IDENTIFIED BY 'cloudera'"
mysql --user=root --password= -e "CREATE DATABASE oozie DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci"
mysql --user=root --password= -e "GRANT ALL ON oozie.* TO 'oozie'@'%' IDENTIFIED BY 'cloudera'"
mysql --user=root --password= -e "CREATE DATABASE schemaregistry DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci"
mysql --user=root --password= -e "GRANT ALL ON schemaregistry.* TO 'schemaregistry'@'%' IDENTIFIED BY 'cloudera'"
mysql --user=root --password= -e "CREATE DATABASE smm  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci"
mysql --user=root --password= -e "GRANT ALL ON smm.* TO 'smm'@'%' IDENTIFIED BY 'cloudera'"
mysql --user=root --password= -e "FLUSH PRIVILEGES"
